In [1]:
#importing the required libraries

import numpy as np
import pandas as pd

In [2]:
#reading the .csv files

movie=pd.read_csv('tmdb_5000_movies.csv')

In [3]:
credits=pd.read_csv('tmdb_5000_credits.csv')

In [4]:
movie.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [5]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [6]:
movie.shape

(4803, 20)

In [7]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
#merging the 2 .csv files

final=pd.merge(movie,credits,left_on='id',right_on='movie_id')[['id','original_title','genres','keywords','overview','cast','crew']]

In [9]:
final.head()

,id,original_title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [10]:
# checking if there are any null values
final.isnull().sum()

id                0
original_title    0
genres            0
keywords          0
overview          3
cast              0
crew              0
dtype: int64

In [11]:
#dropping the null values

final.dropna(subset=['overview'],inplace=True)

In [12]:
final.isnull().sum()

id                0
original_title    0
genres            0
keywords          0
overview          0
cast              0
crew              0
dtype: int64

In [13]:
final['genres'][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [14]:
# converting above genres data into suitable format
import ast
genres=[]
def convert(s):
    l1=[]
    for i in ast.literal_eval(s):
        l1.append(i['name'])
        if i['name'] not in genres:
            genres.append(i['name'])
    text=l1[:]
   
    l1=[]
    return text

In [15]:
final['genres']=final['genres'].apply(convert)

In [16]:
final['genres'].head()

0    [Action, Adventure, Fantasy, Science Fiction]
1                     [Adventure, Fantasy, Action]
2                       [Action, Adventure, Crime]
3                 [Action, Crime, Drama, Thriller]
4             [Action, Adventure, Science Fiction]
Name: genres, dtype: object

In [17]:
print("Genres present in the dataset:\n",genres)

Genres present in the dataset:
 ['Action', 'Adventure', 'Fantasy', 'Science Fiction', 'Crime', 'Drama', 'Thriller', 'Animation', 'Family', 'Western', 'Comedy', 'Romance', 'Horror', 'Mystery', 'History', 'War', 'Music', 'Documentary', 'Foreign', 'TV Movie']

In [18]:
print("Number of genres in the dataset:\n",len(genres))

Number of genres in the dataset:
 20

In [19]:
# converting keywords column into suitable format

final['keywords']=final['keywords'].apply(convert)

In [20]:
final['keywords'].head()

0    [culture clash, future, space war, space colon...
1    [ocean, drug abuse, exotic island, east india ...
2    [spy, based on novel, secret agent, sequel, mi...
3    [dc comics, crime fighter, terrorist, secret i...
4    [based on novel, mars, medallion, space travel...
Name: keywords, dtype: object

In [21]:
final['overview']=final['overview'].apply(lambda x : x.split(' '))

In [22]:
final.head()

,id,original_title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bond’s, past, send...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [23]:
# converting the cast column into suitable format
def fetch_cast(text):
    L=[]
    counter=0
    for i in ast.literal_eval(text):
            if counter<3:
                L.append(i['name'])
            else:
                break
            counter+=1
    L1=L[:]
    L.clear()
    return L1

In [24]:
final['cast']=final['cast'].apply(fetch_cast)

In [25]:
final.head()

,id,original_title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bond’s, past, send...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [26]:
#fecthing the movie director from the crew column
def fetch_director(text):
    L=[]
    for i in ast.literal_eval(text):
        if i['job']=='Director':
            L.append(i['name'])
            break
    L1=L[:]
    L.clear()
    return L1

In [27]:
final['crew']=final['crew'].apply(fetch_director)

In [28]:
final.head()

,id,original_title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bond’s, past, send...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [29]:
#combining the movie metadata into a final 'tags' column

final['tags']=final['genres']+final['keywords']+final['overview']+final['cast']+final['crew']

In [30]:
def remove_space(L):
    L1=[]
    for i in L:
        L1.append(i.replace(' ',''))
    
    L2=L1[:] 
    L1.clear()
    return L2

In [31]:
final['tags']=final['tags'].apply(remove_space)

In [32]:
final.head()

,id,original_title,genres,keywords,overview,cast,crew,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"[Action, Adventure, Fantasy, ScienceFiction, c..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],"[Adventure, Fantasy, Action, ocean, drugabuse,..."
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bond’s, past, send...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],"[Action, Adventure, Crime, spy, basedonnovel, ..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],"[Action, Crime, Drama, Thriller, dccomics, cri..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],"[Action, Adventure, ScienceFiction, basedonnov..."

In [33]:
final['tags']=final['tags'].apply(lambda x:" ".join(x))

In [34]:
final.head()

,id,original_title,genres,keywords,overview,cast,crew,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],Action Adventure Fantasy ScienceFiction cultur...
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],Adventure Fantasy Action ocean drugabuse exoti...
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bond’s, past, send...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],Action Adventure Crime spy basedonnovel secret...
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],Action Crime Drama Thriller dccomics crimefigh...
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],Action Adventure ScienceFiction basedonnovel m...

In [35]:
final['tags']=final['tags'].apply(lambda x:x.lower())

In [36]:
final.head()

,id,original_title,genres,keywords,overview,cast,crew,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],action adventure fantasy sciencefiction cultur...
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],adventure fantasy action ocean drugabuse exoti...
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bond’s, past, send...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],action adventure crime spy basedonnovel secret...
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],action crime drama thriller dccomics crimefigh...
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],action adventure sciencefiction basedonnovel m...

In [37]:
#creating a new column having title in the lower format
def convert(name):
    return name.lower()

final['lower_title']=final['original_title'].apply(convert)

In [38]:
# using count vectorizer to convert text data into vector form

from sklearn.feature_extraction.text import CountVectorizer

In [39]:
cv=CountVectorizer(stop_words='english',max_features=10000)

In [40]:
# transforming tags column into vector form

X = cv.fit_transform(final['tags']).toarray()

In [41]:
X.shape

(4800, 10000)

In [42]:
# using cosine similarity function to find similarity matrix

from sklearn.metrics.pairwise import cosine_similarity

In [43]:
similarity_matrix = cosine_similarity(X)

In [44]:
# checking the shape of the similarity matrix

In [45]:
similarity_matrix.shape

(4800, 4800)

In [46]:
# similarity matrix stores the similarity of each movie with every other movie in the dataset
# and similarity is calculated based on the tags column having the movie metadata

# Generating recommendations based on movie name as input

In [47]:
# storing movie titles in an array

mov=np.array(final['lower_title'])

In [48]:
# defining basic recommendation function to give recommendations based on a movie 

def recommend(movie_name):
    recs=[]
    movie_name=movie_name.lower()
    if movie_name in mov:
        movie_index=final[final['lower_title']== movie_name].index[0]

        L=sorted(list(enumerate(similarity_matrix[movie_index])),reverse=True,key=lambda x:x[1])

        
        for i in L[1:6]:
            print(final.iloc[i[0]]['original_title'])
            recs.append(final.iloc[i[0]]['original_title'])
        return recs
    #if movie name not present in dataset
    else:
        return recs

In [49]:
# testing recommendations
recs=recommend('The Dark Knight rises')

The Dark Knight
Batman Begins
Batman Returns
Batman Forever
Batman

In [50]:
print(recs)

['The Dark Knight', 'Batman Begins', 'Batman Returns', 'Batman Forever', 'Batman']

In [51]:
recs=recommend('Avengers: age of ultron')

Iron Man
The Avengers
Iron Man 3
Captain America: Civil War
Iron Man 2

In [52]:
recs=recommend('spectre')

Quantum of Solace
Never Say Never Again
Skyfall
From Russia with Love
Thunderball

In [53]:
recs=recommend('Minions')

Despicable Me 2
The Croods
The Master of Disguise
Penguins of Madagascar
Cars 2

# Generating Recommendations based on Actor name as input

In [54]:
final['cast'].head()

0    [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1       [Johnny Depp, Orlando Bloom, Keira Knightley]
2        [Daniel Craig, Christoph Waltz, Léa Seydoux]
3        [Christian Bale, Michael Caine, Gary Oldman]
4      [Taylor Kitsch, Lynn Collins, Samantha Morton]
Name: cast, dtype: object

In [55]:
# converting cast column into lower format

def convert_cast(name):
    l1=[]
    for i in name:
        l1.append(i.lower())
    return l1

In [56]:
final['lower_cast']=final['cast'].apply(convert_cast)

In [57]:
final['lower_cast'].head()

0    [sam worthington, zoe saldana, sigourney weaver]
1       [johnny depp, orlando bloom, keira knightley]
2        [daniel craig, christoph waltz, léa seydoux]
3        [christian bale, michael caine, gary oldman]
4      [taylor kitsch, lynn collins, samantha morton]
Name: lower_cast, dtype: object

In [58]:
l1=[]
def listt(c):
    l1.append(c)
    return l1

listt_cast=[]
for i in range(10):
    final['cast']

In [59]:
listt_cast=final['lower_cast'].tolist()

In [60]:

#finding actor's one movie and recommending similar

def recommend(actor_name):
    recs=[]
    flag=0
    actor_name=actor_name.lower()
    for i in range(len(listt_cast)):
        if actor_name in listt_cast[i]:
            
          
            print("yep")
            flag=1
            title= final.iloc[i]['lower_title']
            
            movie_index=final[final['lower_title']== title].index[0]

            L=sorted(list(enumerate(similarity_matrix[movie_index])),reverse=True,key=lambda x:x[1])


            for i in L[1:6]:
                print(final.iloc[i[0]]['original_title'])
                recs.append(final.iloc[i[0]]['original_title'])
            return recs
                
    #if movie name not present in dataset
    if flag==0:
            print("nah")

In [61]:
hero='Daniel Craig'

rec=recommend(hero)

yep
Quantum of Solace
Never Say Never Again
Skyfall
From Russia with Love
Thunderball

In [62]:
#finding all movies of an actor
def get_movies(actor_name):
    recs=[]
    flag=0
    actor_name=actor_name.lower()
    for i in range(len(listt_cast)):
        if actor_name in listt_cast[i]:
            
            flag=1
            title= final.iloc[i]['original_title']
            
            recs.append(title)
    return recs
                
    #if movie name not present in dataset
    if flag==0:
            return recs

In [63]:
hero='ben barnes'
x=get_movies(hero)

In [64]:
def final_movs(x):
    if len(x)>5:
        return x[:5]
    else:
        return x

In [65]:
movies=final_movs(x)
print(movies)

['The Chronicles of Narnia: Prince Caspian', 'Seventh Son', 'Easy Virtue']

# Recommendations based on movie name or actor name

In [66]:
#final recommendation function for both movie name and actor name

def recommend(movie_name):
    recs=[]
    flag=0
    movie_name=movie_name.lower()
    
    #checking if movie name is present
    if movie_name in mov:
        flag=1
        
        movie_index=final[final['lower_title']== movie_name].index[0]
        
    #case when actor name is entered, checking if its present
    else:
        actor_name=movie_name.lower()
        for i in range(len(listt_cast)):
            if actor_name in listt_cast[i]:
                
                flag=2
                
                title= final.iloc[i]['lower_title']
                break
        if flag==2:
            movie_index=final[final['lower_title']== title].index[0]
        
        
    if flag==1 or flag==2:
        
        #finding movies similar to given movie
        L=sorted(list(enumerate(similarity_matrix[movie_index])),reverse=True,key=lambda x:x[1])
        
        #recommending top 5 most similar movies
        for i in L[1:6]:
#             print(final.iloc[i[0]]['original_title'])
            recs.append(final.iloc[i[0]]['original_title'])
        return recs
    
    #if movie/actor name not present in dataset
    else:
        return recs

In [67]:
# recommendations by entering movie name

rec=recommend('skyfall')
print(rec)

['Spectre', 'Never Say Never Again', 'Quantum of Solace', 'Octopussy', 'Dr. No']

In [68]:
rec=recommend('Iron man')
print(rec)

['Iron Man 2', 'Iron Man 3', 'Avengers: Age of Ultron', 'Captain America: Civil War', 'The Avengers']

In [69]:
# recommendations based on actor name

rec=recommend('chris evans')
print(rec)

['Avengers: Age of Ultron', 'Captain America: Civil War', 'Iron Man 3', 'Iron Man', 'Captain America: The First Avenger']

In [70]:
rec=recommend('anne hathaway')
print(rec)

['Alice Through the Looking Glass', 'Mirrormask', '千と千尋の神隠し', 'Charlie and the Chocolate Factory', 'The Indian in the Cupboard']

# Evaluating accuracy of recommendations

In [71]:
entered_mov="titanic"
print("Entered movie:\n",entered_mov)
recs=recommend(entered_mov)
print("\nRecommendations:\n",recs)

l1=[]

# basic recommendation function to test accuracy for a particular movie

def find_simil(x,entered_mov):
    c=0
    entered_mov=entered_mov.lower()
    for i in x:
        i=i.lower()
        if i==entered_mov:
            c+=1
    print(c)
    l1.append(c)
    
for movie in recs:
        print("\nCurrent movie:\n",movie)
        recc=recommend(movie)
        print("\nRecommendations for current movie:\n",recc)
        find_simil(recc,entered_mov)
        

 
print("\nAccuracy:\n",(sum(l1)/5)*100,"%")

Entered movie:
 titanic

Recommendations:
 ['Raise the Titanic', 'In the Heart of the Sea', 'The Notebook', 'Captain Phillips', 'Ghost Ship']

Current movie:
 Raise the Titanic

Recommendations for current movie:
 ["Amidst the Devil's Wings", 'Nueve Reinas', 'Titanic', 'Love Me Tender', 'Captain Phillips']
1

Current movie:
 In the Heart of the Sea

Recommendations for current movie:
 ['Moby Dick', 'Titanic', 'Ghost Ship', '20,000 Leagues Under the Sea', 'Poseidon']
1

Current movie:
 The Notebook

Recommendations for current movie:
 ['Lovely, Still', 'La sirène du Mississipi', 'Iris', 'The Big Parade', 'Cyrus']
0

Current movie:
 Captain Phillips

Recommendations for current movie:
 ['Raise the Titanic', 'Titanic', '20,000 Leagues Under the Sea', 'United 93', "Pirates of the Caribbean: Dead Man's Chest"]
1

Current movie:
 Ghost Ship

Recommendations for current movie:
 ['The Black Hole', 'Devil', 'Poseidon', 'In the Heart of the Sea', 'Titanic']
1

Accuracy:
 80.0 %

In [74]:
# testing accuracy of recommendations for various movie inputs 

input_movies=['titanic','iron man','batman',"baby's day out",'jurassic park','x-men','the amazing spider-man','frozen','up','captain america: civil war','avengers:age of ultron','Harry potter and the goblet of fire']

# function to find overall accuracy based on various movie inputs

def find_simil(x,entered_mov):
   
    c=0
    entered_mov=entered_mov.lower()
    for i in x:
        i=i.lower()
        if i==entered_mov:
            c+=1
    print("\nMatch found with entered movie:",c)
    l1.append(c)
    return l1

accuracy_list=[]
for i in range(0,len(input_movies)):
    l1=[]
    print("\nEntered movie:\n",input_movies[i])
    recs=recommend(str(input_movies[i]))
    print("\nRecommendations:\n",recs)
    for j in range(len(recs)):
            print("\nCurrent movie:\n",recs[j])
            recc=recommend(recs[j])
            print("\nRecommendations for current movie:\n",recc)
            l1=find_simil(recc,input_movies[i])
    acc=(sum(l1)/5)
    accuracy_list.append(acc)
        

overall_acc=round((sum(accuracy_list)/12)*100,2)
print("\nOverall accuracy:\n",overall_acc,"%")

Entered movie:
 titanic

Recommendations:
 ['Raise the Titanic', 'In the Heart of the Sea', 'The Notebook', 'Captain Phillips', 'Ghost Ship']

Current movie:
 Raise the Titanic

Recommendations for current movie:
 ["Amidst the Devil's Wings", 'Nueve Reinas', 'Titanic', 'Love Me Tender', 'Captain Phillips']

Match found with entered movie: 1

Current movie:
 In the Heart of the Sea

Recommendations for current movie:
 ['Moby Dick', 'Titanic', 'Ghost Ship', '20,000 Leagues Under the Sea', 'Poseidon']

Match found with entered movie: 1

Current movie:
 The Notebook

Recommendations for current movie:
 ['Lovely, Still', 'La sirène du Mississipi', 'Iris', 'The Big Parade', 'Cyrus']

Match found with entered movie: 0

Current movie:
 Captain Phillips

Recommendations for current movie:
 ['Raise the Titanic', 'Titanic', '20,000 Leagues Under the Sea', 'United 93', "Pirates of the Caribbean: Dead Man's Chest"]

Match found with entered movie: 1

Current movie:
 Ghost Ship

Recommendations for current movie:
 ['The Black Hole', 'Devil', 'Poseidon', 'In the Heart of the Sea', 'Titanic']

Match found with entered movie: 1

Entered movie:
 iron man

Recommendations:
 ['Iron Man 2', 'Iron Man 3', 'Avengers: Age of Ultron', 'Captain America: Civil War', 'The Avengers']

Current movie:
 Iron Man 2

Recommendations for current movie:
 ['Iron Man 3', 'Iron Man', 'Captain America: Civil War', 'Avengers: Age of Ultron', 'Ant-Man']

Match found with entered movie: 1

Current movie:
 Iron Man 3

Recommendations for current movie:
 ['Iron Man 2', 'Iron Man', 'Avengers: Age of Ultron', 'Captain America: Civil War', 'X-Men']

Match found with entered movie: 1

Current movie:
 Avengers: Age of Ultron

Recommendations for current movie:
 ['Iron Man', 'The Avengers', 'Iron Man 3', 'Captain America: Civil War', 'Iron Man 2']

Match found with entered movie: 1

Current movie:
 Captain America: Civil War

Recommendations for current movie:
 ['Captain America: The Winter Soldier', 'Captain America: The First Avenger', 'Iron Man 3', 'Avengers: Age of Ultron', 'Iron Man 2']

Match found with entered movie: 0

Current movie:
 The Avengers

Recommendations for current movie:
 ['Avengers: Age of Ultron', 'Captain America: Civil War', 'Iron Man 3', 'Iron Man', 'Captain America: The First Avenger']

Match found with entered movie: 1

Entered movie:
 batman

Recommendations:
 ['Batman & Robin', 'Batman Begins', 'The Dark Knight Rises', 'Batman Returns', 'The Dark Knight']

Current movie:
 Batman & Robin

Recommendations for current movie:
 ['Batman', 'Batman Forever', 'Batman Begins', 'The Dark Knight', 'The Dark Knight Rises']

Match found with entered movie: 1

Current movie:
 Batman Begins

Recommendations for current movie:
 ['The Dark Knight', 'The Dark Knight Rises', 'Batman', 'Batman & Robin', "Amidst the Devil's Wings"]

Match found with entered movie: 1

Current movie:
 The Dark Knight Rises

Recommendations for current movie:
 ['The Dark Knight', 'Batman Begins', 'Batman Returns', 'Batman Forever', 'Batman']

Match found with entered movie: 1

Current movie:
 Batman Returns

Recommendations for current movie:
 ['The Dark Knight Rises', 'The Dark Knight', 'Batman', 'Batman: The Dark Knight Returns, Part 2', 'Batman & Robin']

Match found with entered movie: 1

Current movie:
 The Dark Knight

Recommendations for current movie:
 ['The Dark Knight Rises', 'Batman Begins', 'Batman Returns', 'Batman Forever', 'Batman']

Match found with entered movie: 1

Entered movie:
 baby's day out

Recommendations:
 ['Three Men and a Baby', 'Superbabies: Baby Geniuses 2', 'Baby Geniuses', 'L!fe Happens', 'Neighbors']

Current movie:
 Three Men and a Baby

Recommendations for current movie:
 ['Neighbors', 'No se Aceptan Devoluciones', "Baby's Day Out", 'L!fe Happens', 'Baby Geniuses']

Match found with entered movie: 1

Current movie:
 Superbabies: Baby Geniuses 2

Recommendations for current movie:
 ['Baby Geniuses', "Baby's Day Out", 'Three Men and a Baby', 'Neighbors', 'L!fe Happens']

Match found with entered movie: 1

Current movie:
 Baby Geniuses

Recommendations for current movie:
 ['As Good as It Gets', 'American Hero', 'Chicago Overcoat', "Jesus' Son", 'Bandits']

Match found with entered movie: 0

Current movie:
 L!fe Happens

Recommendations for current movie:
 ['Jackass Presents: Bad Grandpa', 'Partition', 'Trust', '8 Days', 'Eye for an Eye']

Match found with entered movie: 0

Current movie:
 Neighbors

Recommendations for current movie:
 ['Neighbors 2: Sorority Rising', 'Three Men and a Baby', "Baby's Day Out", 'Baby Geniuses', 'Superbabies: Baby Geniuses 2']

Match found with entered movie: 1

Entered movie:
 jurassic park

Recommendations:
 ['Jurassic World', 'The Lost World: Jurassic Park', 'Jurassic Park III', 'The Land Before Time', 'The Nut Job']

Current movie:
 Jurassic World

Recommendations for current movie:
 ['Jurassic Park', 'The Lost World: Jurassic Park', 'Journey to the Center of the Earth', 'Jurassic Park III', 'A Sound of Thunder']

Match found with entered movie: 1

Current movie:
 The Lost World: Jurassic Park

Recommendations for current movie:
 ['Jurassic World', 'Jurassic Park', 'Jurassic Park III', 'The Helix... Loaded', '疯狂的赛车']

Match found with entered movie: 1

Current movie:
 Jurassic Park III

Recommendations for current movie:
 ['The Lost World: Jurassic Park', 'Jurassic Park', 'Jurassic World', 'Cliffhanger', 'Pandorum']

Match found with entered movie: 1

Current movie:
 The Land Before Time

Recommendations for current movie:
 ['Happy Christmas', '인천상륙작전', 'Flyboys', 'Nicholas Nickleby', 'Le Hussard sur le toit']

Match found with entered movie: 0

Current movie:
 The Nut Job

Recommendations for current movie:
 ['Meet the Deedles', 'Yogi Bear', 'Up', 'Stuart Little 2', 'Zambezia']

Match found with entered movie: 0

Entered movie:
 x-men

Recommendations:
 ['X2', 'X-Men: The Last Stand', 'X-Men: First Class', 'The Wolverine', 'X-Men Origins: Wolverine']

Current movie:
 X2

Recommendations for current movie:
 ['X-Men', 'X-Men: The Last Stand', 'X-Men: First Class', 'X-Men Origins: Wolverine', 'X-Men: Days of Future Past']

Match found with entered movie: 1

Current movie:
 X-Men: The Last Stand

Recommendations for current movie:
 ['X2', 'X-Men', 'X-Men: Days of Future Past', 'X-Men: First Class', 'X-Men Origins: Wolverine']

Match found with entered movie: 1

Current movie:
 X-Men: First Class

Recommendations for current movie:
 ['X-Men: Apocalypse', 'X-Men', 'X2', 'X-Men: The Last Stand', 'X-Men: Days of Future Past']

Match found with entered movie: 1

Current movie:
 The Wolverine

Recommendations for current movie:
 ['X-Men', 'X-Men Origins: Wolverine', 'X-Men: Days of Future Past', 'X2', 'Teenage Mutant Ninja Turtles III']

Match found with entered movie: 1

Current movie:
 X-Men Origins: Wolverine

Recommendations for current movie:
 ['The Wolverine', 'X-Men', 'X2', 'X-Men: The Last Stand', 'X-Men: Apocalypse']

Match found with entered movie: 1

Entered movie:
 the amazing spider-man

Recommendations:
 ['The Amazing Spider-Man 2', 'Spider-Man 3', 'Spider-Man', 'Hook', 'Spider-Man 2']

Current movie:
 The Amazing Spider-Man 2

Recommendations for current movie:
 ['The Amazing Spider-Man', 'Spider-Man 3', 'Spider-Man', 'Forgetting Sarah Marshall', 'Pan']

Match found with entered movie: 1

Current movie:
 Spider-Man 3

Recommendations for current movie:
 ['Spider-Man 2', 'Spider-Man', 'The Amazing Spider-Man 2', 'The Amazing Spider-Man', 'Arachnophobia']

Match found with entered movie: 1

Current movie:
 Spider-Man

Recommendations for current movie:
 ['Spider-Man 3', 'Spider-Man 2', 'The Amazing Spider-Man 2', 'The Amazing Spider-Man', 'Arachnophobia']

Match found with entered movie: 1

Current movie:
 Hook

Recommendations for current movie:
 ['Pan', 'Return to Never Land', 'The Brave Little Toaster', 'Mirrormask', 'Finding Neverland']

Match found with entered movie: 0

Current movie:
 Spider-Man 2

Recommendations for current movie:
 ['Spider-Man 3', 'Spider-Man', 'The Amazing Spider-Man', 'The Amazing Spider-Man 2', 'Hellboy II: The Golden Army']

Match found with entered movie: 1

Entered movie:
 frozen

Recommendations:
 ['Aladdin', 'Spirit: Stallion of the Cimarron', 'The Book of Life', 'Delgo', 'Curious George']

Current movie:
 Aladdin

Recommendations for current movie:
 ['Delgo', 'Frozen', 'Enchanted', 'Never Again', 'The Adventures of Rocky & Bullwinkle']

Match found with entered movie: 1

Current movie:
 Spirit: Stallion of the Cimarron

Recommendations for current movie:
 ['Titan A.E.', 'Frozen', 'Dwegons', 'Aladdin', 'The Book of Life']

Match found with entered movie: 1

Current movie:
 The Book of Life

Recommendations for current movie:
 ['The Brave Little Toaster', 'The Croods', 'Nicholas Nickleby', 'My Big Fat Greek Wedding 2', 'Frozen']

Match found with entered movie: 1

Current movie:
 Delgo

Recommendations for current movie:
 ['Aladdin', 'Frozen', 'Return to Never Land', 'Little Boy', "Happily N'Ever After"]

Match found with entered movie: 1

Current movie:
 Curious George

Recommendations for current movie:
 ['Jungle Shuffle', 'The Book of Life', 'The Croods', 'Frozen', 'George of the Jungle']

Match found with entered movie: 1

Entered movie:
 up

Recommendations:
 ['Raising Helen', 'The Truman Show', 'Memoirs of an Invisible Man', 'Partition', 'Holy Motors']

Current movie:
 Raising Helen

Recommendations for current movie:
 ['Synecdoche, New York', 'Up', 'Memoirs of an Invisible Man', 'Anything Else', 'The Duchess']

Match found with entered movie: 1

Current movie:
 The Truman Show

Recommendations for current movie:
 ['Up', 'Raising Helen', 'Nurse Betty', 'A True Story', 'A Cock and Bull Story']

Match found with entered movie: 1

Current movie:
 Memoirs of an Invisible Man

Recommendations for current movie:
 ['Raising Helen', 'Up', 'Four Single Fathers', 'The Helix... Loaded', 'Down to Earth']

Match found with entered movie: 1

Current movie:
 Partition

Recommendations for current movie:
 ['Blood and Wine', 'I Heart Huckabees', 'Ca$h', 'Theresa Is a Mother', 'The Cookout']

Match found with entered movie: 0

Current movie:
 Holy Motors

Recommendations for current movie:
 ['Trees Lounge', 'Cat on a Hot Tin Roof', 'Albino Alligator', 'On the Waterfront', 'In Cold Blood']

Match found with entered movie: 0

Entered movie:
 captain america: civil war

Recommendations:
 ['Captain America: The Winter Soldier', 'Captain America: The First Avenger', 'Iron Man 3', 'Avengers: Age of Ultron', 'Iron Man 2']

Current movie:
 Captain America: The Winter Soldier

Recommendations for current movie:
 ['Captain America: Civil War', 'Captain America: The First Avenger', 'The Avengers', 'Iron Man 3', 'Ant-Man']

Match found with entered movie: 1

Current movie:
 Captain America: The First Avenger

Recommendations for current movie:
 ['Captain America: Civil War', 'Captain America: The Winter Soldier', 'Saints and Soldiers', 'Red Tails', 'Iron Man 3']

Match found with entered movie: 1

Current movie:
 Iron Man 3

Recommendations for current movie:
 ['Iron Man 2', 'Iron Man', 'Avengers: Age of Ultron', 'Captain America: Civil War', 'X-Men']

Match found with entered movie: 1

Current movie:
 Avengers: Age of Ultron

Recommendations for current movie:
 ['Iron Man', 'The Avengers', 'Iron Man 3', 'Captain America: Civil War', 'Iron Man 2']

Match found with entered movie: 1

Current movie:
 Iron Man 2

Recommendations for current movie:
 ['Iron Man 3', 'Iron Man', 'Captain America: Civil War', 'Avengers: Age of Ultron', 'Ant-Man']

Match found with entered movie: 1

Entered movie:
 avengers:age of ultron

Recommendations:
 []

Entered movie:
 Harry potter and the goblet of fire

Recommendations:
 ['Harry Potter and the Order of the Phoenix', 'Harry Potter and the Prisoner of Azkaban', 'Harry Potter and the Chamber of Secrets', 'Harry Potter and the Half-Blood Prince', "Harry Potter and the Philosopher's Stone"]

Current movie:
 Harry Potter and the Order of the Phoenix

Recommendations for current movie:
 ['Harry Potter and the Prisoner of Azkaban', 'Harry Potter and the Goblet of Fire', 'Harry Potter and the Chamber of Secrets', 'Harry Potter and the Half-Blood Prince', "Harry Potter and the Philosopher's Stone"]

Match found with entered movie: 1

Current movie:
 Harry Potter and the Prisoner of Azkaban

Recommendations for current movie:
 ['Harry Potter and the Chamber of Secrets', 'Harry Potter and the Order of the Phoenix', 'Harry Potter and the Goblet of Fire', 'Harry Potter and the Half-Blood Prince', "Harry Potter and the Philosopher's Stone"]

Match found with entered movie: 1

Current movie:
 Harry Potter and the Chamber of Secrets

Recommendations for current movie:
 ['Harry Potter and the Prisoner of Azkaban', 'Harry Potter and the Order of the Phoenix', 'Harry Potter and the Goblet of Fire', "Harry Potter and the Philosopher's Stone", 'Harry Potter and the Half-Blood Prince']

Match found with entered movie: 1

Current movie:
 Harry Potter and the Half-Blood Prince

Recommendations for current movie:
 ['Harry Potter and the Order of the Phoenix', 'Harry Potter and the Goblet of Fire', 'Harry Potter and the Prisoner of Azkaban', 'Harry Potter and the Chamber of Secrets', "Harry Potter and the Philosopher's Stone"]

Match found with entered movie: 1

Current movie:
 Harry Potter and the Philosopher's Stone

Recommendations for current movie:
 ['Harry Potter and the Chamber of Secrets', 'Harry Potter and the Goblet of Fire', 'Harry Potter and the Prisoner of Azkaban', 'Harry Potter and the Order of the Phoenix', 'Harry Potter and the Half-Blood Prince']

Match found with entered movie: 1

Overall accuracy:
 76.67 %